{
 "title": "Ceph Cluster",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Cluster Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 } },
  {
   "title": "MONs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_mon_metadata)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSD Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (instance) (ceph_disk_occupation))"
    }
   ]
  },
  {
   "title": "MDS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_mds_metadata)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RGW Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_rgw_metadata)" }
   ]
  },
  {
   "title": "iSCSI Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ceph_iscsi_gateway_tpg_total)"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max by (ceph_daemon) (ceph_osd_metadata))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_metadata)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unused Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes - ceph_cluster_total_used_bytes"
    }
   ]
  },
  { "title": "Cluster Flags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "content": "<h2 style=\"text-align: center;\">Cluster Flags:</h2>"
  },
  {
   "title": "SCRUB",
   "type": "singlestat",
   "description": "Scrub activity takes place daily basis across the OSD's and performs object size and attribute checks. Scrub activity can be controlled with the \"ceph osd scrub\" command.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "2*scalar(ceph_osd_flag_noscrub) + scalar(ceph_pg_scrubbing >bool 0)"
    }
   ]
  },
  {
   "title": "DEEP",
   "type": "singlestat",
   "description": "Deep scrub acts on the objects within placement groups (PGs). Objects are read, and checksum's compared to protect against silent bit-rot events. Although a weekly activity, in large clusters is normal to see deep-scrub active on a daily basis. Scrub activity can be controlled with the \"ceph osd scrub\" command.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "2*scalar(ceph_osd_flag_nodeep_scrub) + scalar(ceph_pg_deep >bool 0)"
    }
   ]
  },
  {
   "title": "RECOVERY",
   "type": "singlestat",
   "description": "With the recovery flag enabled, disruption in the cluster will result in data being recreated to freespace within the cluster to honor the pool's protection schema. Under some circumstances, you may use the norecover flag to prevent automatic recovery.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "2*scalar(ceph_osd_flag_norecover) + scalar(ceph_pg_recovering >bool 0)"
    }
   ]
  },
  {
   "title": "BACKFILL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "2*scalar(ceph_osd_flag_nobackfill) + scalar(ceph_pg_backfilling >bool 0)"
    },
    {}
   ]
  },
  {
   "title": "REBALANCE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "2*scalar(ceph_osd_flag_norebalance)"
    }
   ]
  },
  {
   "title": "OUT",
   "type": "singlestat",
   "description": "The OUT flag setting allows the mon's to mark OSD's as out of the configuration when they stop sending hearbeats to the mon's. By marking them OUT, recovery takes place. However, for planned maintenance you can set the cluster to noout to disable this behavior.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "2*scalar(ceph_osd_flag_noout)" }
   ]
  },
  {
   "title": "DOWN",
   "type": "singlestat",
   "description": "The down feature allows OSD's to mark their peers as DOWN when they are not reachable. However, if there is a poor network or planned outages, you may want to set this flag to nodown to prevent OSD's flapping between up/down states",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "2*scalar(ceph_osd_flag_nodown) + scalar(ceph_pg_down >bool 0)"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Capacity - Past 7 Days",
     "type": "graph",
     "description": "Shows the Capacity within the cluster over the past 7 days",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Used",
       "expr": "scalar(ceph_cluster_total_used_bytes)",
       "legendFormat": "Used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Raw Capacity",
       "expr": "scalar(ceph_cluster_total_bytes)",
       "legendFormat": "Raw",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pool Capacity - Past 7 Days",
     "type": "graph",
     "description": "Shows the Capacity within each pool over the past 7 days",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Used",
       "expr": "max by (name) (\n  ceph_pool_bytes_used / (ceph_pool_bytes_used + ceph_pool_max_avail) * 100 + on (pool_id) group_left (name) ceph_pool_metadata\n)",
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "RADOS Object History - Past 7 Days",
     "type": "graph",
     "description": "Shows the Capacity within the cluster over the past 7 days",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "RADOS Object Count" }
     ],
     "targets": [
      {
       "alias": "Used",
       "expr": "scalar(ceph_cluster_total_objects)",
       "legendFormat": "RADOS Objects",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Distribution of PGs per OSD",
     "type": "graph",
     "description": "Each bar indicates the number of OSD's that have a PG count in a specific range as shown on the x axis.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "# of OSDs" }
     ],
     "targets": [
      { "expr": "ceph_osd_numpg\n", "legendFormat": "PGs per OSD" }
     ]
    },
    {
     "title": "OSDs by PG Counts",
     "type": "table",
     "description": "This table shows all OSDs sorted by their PG Count. The PG count is color coded.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "ceph_osd_numpg * on(ceph_daemon) group_left(instance,device) ceph_disk_occupation"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Daemon Version Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "MONs",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "label_replace(ceph_mon_metadata,\"short_vers\",\"$1\",\"ceph_version\",\"ceph version(.*) (.*) (.*) (.*)\")"
      }
     ]
    },
    {
     "title": "OSDs",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "targets": [
      {
       "expr": "label_replace(ceph_osd_metadata,\"short_vers\",\"$1\",\"ceph_version\",\"ceph version(.*) (.*) (.*) (.*)\")",
       "legendFormat": "{{id}} - {{short_vers}}"
      }
     ]
    },
    {
     "title": "RGWs",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "label_replace(ceph_rgw_metadata,\"short_vers\",\"$1\",\"ceph_version\",\"ceph version(.*) (.*) (.*) (.*)\")"
      }
     ]
    },
    {
     "title": "MDSs",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "label_replace(ceph_mds_metadata,\"short_vers\",\"$1\",\"ceph_version\",\"ceph version(.*) (.*) (.*) (.*)\")",
       "legendFormat": "{{id}} - {{short_vers}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 16, "y": 10 } }
   ]
  }
 ]
}