{
 "title": "Ceph Health",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "osd_servers", "query": "ceph_disk_occupation" },
   { "name": "disk_full_threshold", "query": "85" },
   {
    "name": "mon_servers",
    "query": "label_values(ceph_mon_quorum_status, ceph_daemon)"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "description": "Shows the overall health of the ceph cluster.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "Cluster Health History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health History - Last 3 days",
     "type": "graph",
     "description": "The chart plots the clusters health, over time. The colored bands show 3 distinct areas; green (OK), yellow(WARN) and red(ERROR). The plot line in blue is this clusters current health, so you can see over time how long the cluster spends in an OK, WARN or ERROR state",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "ceph_health_status ", "legendFormat": "Ceph Health" }
     ]
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
     "content": "<h2 style=\"text-align: center;\">MONs</h2>"
    },
    {
     "title": "$mon_servers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 5 },
     "repeat": "mon_servers",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "label_replace(ceph_mon_quorum_status{ceph_daemon=~\"[[mon_servers]]\"},\"mon_host\",\"$2\",\"ceph_daemon\",\"(.*)_(.*)\")"
      }
     ]
    },
    {
     "type": "text",
     "description": "Show cluster flags that determine automatic maintenance and recovery operations",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
     "content": "<h2 style=\"text-align: center;\">Cluster Flags:</h2>"
    },
    {
     "title": "SCRUB",
     "type": "singlestat",
     "description": "Scrub activity takes place daily basis across the OSD's and performs object size and attribute checks. Scrub activity can be controlled with the \"ceph osd scrub\" command.",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "2*scalar(ceph_osd_flag_noscrub) + scalar(ceph_pg_scrubbing >bool 0)"
      }
     ]
    },
    {
     "title": "DEEP",
     "type": "singlestat",
     "description": "Deep scrub acts on the objects within placement groups (PGs). Objects are read, and checksum's compared to protect against silent bit-rot events. Although a weekly activity, in large clusters is normal to see deep-scrub active on a daily basis. Scrub activity can be controlled with the \"ceph osd scrub\" command.",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "2*scalar(ceph_osd_flag_nodeep_scrub) + scalar(ceph_pg_deep >bool 0)"
      }
     ]
    },
    {
     "title": "OUT",
     "type": "singlestat",
     "description": "The OUT flag setting allows the mon's to mark OSD's as out of the configuration when they stop sending hearbeats to the mon's. By marking them OUT, recovery takes place. However, for planned maintenance you can set the cluster to noout to disable this behavior.",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "2*scalar(ceph_osd_flag_noout)" }
     ]
    },
    {
     "title": "DOWN",
     "type": "singlestat",
     "description": "The down feature allows OSD's to mark their peers as DOWN when they are not reachable. However, if there is a poor network or planned outages, you may want to set this flag to nodown to prevent OSD's flapping between up/down states",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "2*scalar(ceph_osd_flag_nodown) + scalar(ceph_pg_down >bool 0)"
      }
     ]
    },
    {
     "title": "BACKFILL",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "2*scalar(ceph_osd_flag_nobackfill) + scalar(ceph_pg_backfilling >bool 0)"
      },
      {}
     ]
    },
    {
     "title": "REBALANCE",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "2*scalar(ceph_osd_flag_norebalance)"
      }
     ]
    },
    {
     "title": "RECOVERY",
     "type": "singlestat",
     "description": "With the recovery flag enabled, disruption in the cluster will result in data being recreated to freespace within the cluster to honor the pool's protection schema. Under some circumstances, you may use the norecover flag to prevent automatic recovery.",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "2*scalar(ceph_osd_flag_norecover) + scalar(ceph_pg_recovering >bool 0)"
      }
     ]
    },
    {
     "title": "$mon_servers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "label_replace(ceph_mon_quorum_status{ceph_daemon=~\"[[mon_servers]]\"},\"mon_host\",\"$2\",\"ceph_daemon\",\"(.*)_(.*)\")"
      }
     ]
    },
    {
     "type": "text",
     "description": "Shows which OSD hosts have all defined osd daemons in a down state",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
     "content": "<h2 style=\"text-align: center;\">OSD<br>Hosts<br>Down</h2>"
    },
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 10, "x": 10, "y": 8 },
     "targets": [
      {
       "expr": "(count by(instance) (ceph_disk_occupation * on(ceph_daemon) group_right(instance) ceph_osd_up == 0) - count by(instance) (ceph_disk_occupation))"
      }
     ]
    },
    {
     "title": "$mon_servers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "label_replace(ceph_mon_quorum_status{ceph_daemon=~\"[[mon_servers]]\"},\"mon_host\",\"$2\",\"ceph_daemon\",\"(.*)_(.*)\")"
      }
     ]
    }
   ]
  },
  {
   "title": "RADOS Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object Summary",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
     "targets": [
      {
       "alias": "Objects",
       "expr": "ceph_cluster_total_objects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total Objects",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      { "legendFormat": "Objects misplaced" },
      { "legendFormat": "Objects degraded" },
      { "legendFormat": "Objects unfound" }
     ]
    },
    {
     "title": "PG Summary",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 6 },
     "targets": [
      { "expr": "ceph_pg_total", "legendFormat": "PGs" },
      { "expr": "ceph_pg_active", "legendFormat": "PGs Active" },
      { "expr": "ceph_pg_clean", "legendFormat": "PGs Active+clean" },
      { "expr": "ceph_pg_peering", "legendFormat": "PGs Peering" },
      { "expr": "ceph_pg_unknown", "legendFormat": "PG's Unknown" }
     ]
    }
   ]
  },
  {
   "title": "Storage Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks Near Full",
     "type": "table",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "ceph_osd_stat_bytes_used / ceph_osd_stat_bytes * 100 > $disk_full_threshold",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD's Down",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 3, "y": 14 },
     "targets": [
      {
       "expr": "label_replace(ceph_osd_up,\"_id\",\"$1\",\"ceph_daemon\",\"osd.(.*)\") * on(ceph_daemon) \n  group_left(osd_host,device) label_replace(ceph_disk_occupation,\"osd_host\",\"$1\",\"instance\",\"(.+?)\\\\.(.*)\") < 0.5"
      }
     ]
    },
    {
     "title": "OSDs Out",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 9, "y": 14 },
     "targets": [
      {
       "expr": "label_replace(ceph_osd_in,\"_id\",\"$1\",\"ceph_daemon\",\"osd.(.*)\") * on(ceph_daemon) \n  group_left(osd_host,device) label_replace(ceph_disk_occupation,\"osd_host\",\"$1\",\"instance\",\"(.+?)\\\\.(.*)\") < 0.5"
      }
     ]
    },
    {
     "title": "OSDs with High PG Counts",
     "type": "table",
     "description": "This table shows all OSDs with > 275 PG's",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
     "targets": [
      {
       "expr": "(ceph_osd_numpg > 275) * on(ceph_daemon) group_left(instance,device) ceph_disk_occupation"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 6, "y": 21 } },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 16, "y": 21 } }
   ]
  }
 ]
}